FROM bellsoft/liberica-openjdk-alpine:17

WORKDIR /app

COPY gradlew .
COPY gradle gradle
COPY build.gradle .
COPY settings.gradle .

RUN chmod +x gradlew

EXPOSE 8080

ENTRYPOINT ["./gradlew", "bootRun"]