CREATE TABLE posts (
       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
       title VARCHAR(255) NOT NULL,
       slug VARCHAR(255) NOT NULL,
       content_md TEXT NOT NULL,
       content_html TEXT NOT NULL,
       author VARCHAR(255) NOT NULL,
       create_at TIMESTAMP NOT NULL,
       update_at TIMESTAMP NOT NULL
);

CREATE TABLE tags (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      name VARCHAR(100) NOT NULL UNIQUE,
      post_cnt INT NOT NULL DEFAULT 0,
      create_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE post_tags (
      post_id BIGINT NOT NULL,
      tag_id BIGINT NOT NULL,

      PRIMARY KEY (post_id, tag_id),

      CONSTRAINT fk_post_tags_post
          FOREIGN KEY (post_id)
              REFERENCES posts (id)
              ON DELETE CASCADE,

      CONSTRAINT fk_post_tags_tag
          FOREIGN KEY (tag_id)
              REFERENCES tags (id)
              ON DELETE CASCADE
);